In [1]:
import numpy as np
import pandas as pd

In [2]:
auto =pd.read_csv("autos_small.csv")

In [3]:
auto

price  ... vehicleType
0       400  ...       kombi
1      3500  ...      cabrio
2      2200  ...       kombi
3      4000  ...   limousine
4      2600  ...      cabrio
...     ...  ...         ...
9995   2650  ...  kleinwagen
9996   9600  ...         bus
9997   1500  ...       kombi
9998    970  ...  kleinwagen
9999   7990  ...   limousine

[10000 rows x 11 columns]

In [4]:
auto = auto[auto["price"]<auto["price"].quantile(0.99)]

In [5]:
auto= auto[auto["yearOfRegistration"]<auto["yearOfRegistration"].quantile(0.999)]

In [6]:
auto["yearOfRegistration"].max()

2017

In [7]:
auto = auto[auto["yearOfRegistration"]>auto["yearOfRegistration"].quantile(0.001)]

In [8]:
X =auto["yearOfRegistration"].values
y=auto['price'].values

In [9]:
X

array([1992, 1996, 1998, ..., 1999, 2002, 2012])

In [10]:
y

array([ 400, 3500, 2200, ..., 1500,  970, 7990])

SPLITING INTO TRAINING AND TEST DATA

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=1000)

FEATURE SCALING 

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler =StandardScaler()
scaler1 =StandardScaler()
X_train = scaler.fit_transform(X_train.reshape(-1,1))
X_test = scaler.transform(X_test.reshape(-1,1))
y_train = scaler1.fit_transform(y_train.reshape(-1,1))
y_test = scaler1.transform(y_test.reshape(-1,1))

In [ ]:
# 4. Apply various regression models and find out which model is the best for this dataset

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr =LinearRegression()

In [17]:
lr.fit(X_train.reshape(-1,1),y_train.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
y_pred =lr.predict(X_test.reshape(-1,1))

In [19]:
y_pred

array([[-0.01779752],
       [ 0.49329167],
       [-0.24494826],
       ...,
       [-0.0745852 ],
       [ 0.03899017],
       [ 0.15256555]])

In [20]:
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
r2_score(y_test, y_pred)

0.14347109441541972

In [22]:
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Coefficient of determination: 0.14


# others

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
auto2 =pd.read_csv("autos_small.csv")

In [ ]:
cols=['name', 'yearOfRegistration', 'monthOfRegistration', 'gearbox', 'model', 'brand', 'vehicleType']

In [ ]:
auto2.drop(cols,axis=1,inplace=True)

In [ ]:
auto2

price  powerPS  kilometer fuelType
0       400       89      60000   benzin
1      3500      150     125000      NaN
2      2200      150     150000   benzin
3      4000        0     150000   diesel
4      2600       41     150000   diesel
...     ...      ...        ...      ...
9995   2650       80     150000   benzin
9996   9600      140     150000   diesel
9997   1500      101     150000      NaN
9998    970       58     150000   benzin
9999   7990      101      60000   benzin

[10000 rows x 4 columns]

In [ ]:
auto2['fuelType'] = auto2['fuelType'].fillna(auto2['fuelType'].mode()[0])

In [ ]:
auto2

price  powerPS  kilometer fuelType
0       400       89      60000   benzin
1      3500      150     125000   benzin
2      2200      150     150000   benzin
3      4000        0     150000   diesel
4      2600       41     150000   diesel
...     ...      ...        ...      ...
9995   2650       80     150000   benzin
9996   9600      140     150000   diesel
9997   1500      101     150000   benzin
9998    970       58     150000   benzin
9999   7990      101      60000   benzin

[10000 rows x 4 columns]

In [ ]:
auto2 = pd.get_dummies(auto2, columns=['fuelType'],drop_first=True)

In [ ]:
auto2

price  powerPS  ...  fuelType_hybrid  fuelType_lpg
0       400       89  ...                0             0
1      3500      150  ...                0             0
2      2200      150  ...                0             0
3      4000        0  ...                0             0
4      2600       41  ...                0             0
...     ...      ...  ...              ...           ...
9995   2650       80  ...                0             0
9996   9600      140  ...                0             0
9997   1500      101  ...                0             0
9998    970       58  ...                0             0
9999   7990      101  ...                0             0

[10000 rows x 9 columns]

In [ ]:
X = auto2[['price', 'powerPS', 'kilometer']]

In [ ]:
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns

In [ ]:
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                          for i in range(len(X.columns))]
  
print(vif_data)

     feature       VIF
0      price  1.002417
1    powerPS  1.113691
2  kilometer  1.115448
